version: "3"

services:
  data:
    image: node:12
    command: yarn data:watch
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - yarncache:/home/node/yarn
    environment:
      YARN_CACHE_FOLDER: /home/node/yarn
      TS_NODE_COMPILER_OPTIONS: '{"module":"commonjs"}'

  app:
    image: node:12
    command: yarn start
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - yarncache:/home/node/yarn
    environment:
      YARN_CACHE_FOLDER: /home/node/yarn
      CHOKIDAR_USEPOLLING: "true"

volumes:
  yarncache:
