Rejected Properties:
  tags:
    # Tronket upgrades
    - Trinket

    #Includes
    # - Flask items (Corrupting Potion)
    # - Doran's Items
    # - Guardian (ARAM Doran)
    # - Cull
    - Lane

    #Includes
    # - Oracles Extract
    # - Elixirs
    # - Cookies
    # - Wards
    - Consumable

#Quote Excluded IDs since they are strings in the json blob.
Excluded IDs:
  #The Cull is a "DoransItems" without the tag
  - "1083" #Cull

  #Bogus enchantments
  #They just show up as shoes
  - "3675"
  - "3672"
  - "3673"
  - "3671"

  #Kalista plz
  - "3599" #The Black Spear

  #Poacher's Dirk you're silly
  #You turn into things that turn into other things
  - "3252"

  #Seige mode plz
  - "3631" #Siege Ballista
  - "3634" #Tower: Beam of Ruination
  - "3635" #Port Pad
  - "3636" #Tower: Storm Bulwark
  - "3640" #Flash Zone
  - "3641" #Vanguard Banner
  - "3642" #Siege Refund
  - "3643" #Entropy Field
  - "3647" #Shield Totem


Remove from Map:
  #Quick Charge is only for certain events in SR
  "3007":  #Archangel's Staff (Quick Charge)
    - '11' # - Summoner's Rift
  "3008":  #Manamune (Quick Charge)
    - '11' # - Summoner's Rift
  "3029":  #Rod of Ages (Quick Charge)
    - '11' # - Summoner's Rift